### ISSUE TITLE
collateral amount is off, Your Vaults shows the different collateral amount for same vault from Your Positions

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#304] opened 2022-04-06 07:36 UTC
**Describe the bug**
Collateral amount is off, the vaults show I have 16 ETH but the position shows I have only 8 ETH

**To Reproduce**

1. Opened short amount twice with 8 ETH each
2. Check the /positions

**Expected behavior**

**Screenshots**
<img width="921" alt="image" src="https://user-images.githubusercontent.com/26922518/161920927-5069fe5d-dad5-46d2-a87b-8b3d9b647a23.png">

**Additional context**

**Comment by KMKoushik** [comment] 2022-05-10 09:14
This is because of the polling issue I guess, which got fixed with Esther's changes most probably. Can't reproduce anymore

**Closed by KMKoushik** 2022-05-10 09:14 UTC
Labels: bug, frontend, positions page, 3 star
