### ISSUE TITLE
shortDebt incorrect if you mint + sell manually

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#163] opened 2022-02-12 01:32 UTC
**Describe the bug**
shortDebt + mintedDebt should be equal to total debt. I am technically only short 1 oSQTH but the site thinks I am short more - the shortDebt number is wrong

**To Reproduce**
- Opened a short using short helper 
- Fully closed short using short helper 
- Minted oSQTH 
- Went short 1 oSQTH

**Expected behavior**
shortDebt + mintedDebt = totalDebt

**Screenshots**
<img width="1012" alt="Screen Shot 2022-02-11 at 5 30 18 PM" src="https://user-images.githubusercontent.com/13340486/153690986-4042d21d-47c6-4111-836d-409536f5ddd4.png">

**Comment by yichiehliu** [comment] 2022-04-22 18:09
@alexisgauba are u still able to reproduce this bug? Cuz I couldn't reproduce it
<img width="979" alt="image" src="https://user-images.githubusercontent.com/26922518/164770753-bdfdfbea-661c-4954-abbe-d46586d50567.png">

**Comment by yichiehliu** [comment] 2022-04-24 10:41
The bug is not reproducible, will close this issue for now.

**Closed by yichiehliu** 2022-04-24 10:41 UTC
Labels: bug, frontend, positions page, 3 star
